# Generated by Django 4.2.6 on 2024-06-04 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_alter_category_options_alter_postcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(related_name='Подписчики', to=settings.AUTH_USER_MODEL),
        ),
    ]
